name: Deploy to GitHub Pages
on: [push]
permissions:
  id-token: write    # 解决权限错误
  contents: write    # 允许提交代码
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
      - name: Build Site
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3  # 官方推荐部署工具
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public               # Hexo生成目录